/**
 * 錯誤代碼常量
 */
export const ErrorCode = {
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  NOT_FOUND: 'NOT_FOUND',
  UNAUTHORIZED: 'UNAUTHORIZED',
  REAUTH_REQUIRED: 'REAUTH_REQUIRED',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
} as const
