/**
 * 錯誤代碼常量
 */
export const ErrorCode = {
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  NOT_FOUND: 'NOT_FOUND',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  REAUTH_REQUIRED: 'REAUTH_REQUIRED',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  NOT_IMPLEMENTED: 'NOT_IMPLEMENTED',
} as const
